/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.EntidadUsuarios;
import sql.UsuarioSQL;

/**
 *
 * @author basti
 */
public class Ventana_Ingreso_Usuario extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    UsuarioSQL usql = new UsuarioSQL();

    /**
     * Creates new form Ventana_Ingreso_Usuario
     */
    public Ventana_Ingreso_Usuario() {
        initComponents();
        listar();
    }

    void listar() {
        List<EntidadUsuarios> lista = usql.listar();
        modelo = (DefaultTableModel) table_usuarios.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getRut_personal_PK_bd();
            ob[1] = lista.get(i).getNombre_bd();
            ob[2] = lista.get(i).getApellido_bd();
            ob[3] = lista.get(i).getRol_nombre_bd();
            modelo.addRow(ob);
        }
        table_usuarios.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        nuevo_usuario_rol = new javax.swing.JComboBox<>();
        nuevo_usuario_apellido = new javax.swing.JTextField();
        nuevo_usuario_rut = new javax.swing.JTextField();
        nuevo_usuario_nombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_usuarios = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Nuevo Usuario");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Bicon.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 249, 249));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Bytes7575.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 30, 119, 48);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nuevo Usuario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 40, 196, 29);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevousuario.png"))); // NOI18N
        jLabel3.setText("Datos Usuarios");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 20, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Rut");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(120, 60, 24, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Rol");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(120, 240, 30, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Apellido");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 180, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, 120, 57, 30);

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar-documento.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modificar);
        btn_modificar.setBounds(160, 370, 120, 41);

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agregar);
        btn_agregar.setBounds(30, 320, 110, 40);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-eliminar.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_eliminar);
        btn_eliminar.setBounds(160, 320, 120, 41);

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar32.png"))); // NOI18N
        btn_limpiar.setText("Limpiar");
        jPanel2.add(btn_limpiar);
        btn_limpiar.setBounds(30, 370, 110, 40);

        nuevo_usuario_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));
        jPanel2.add(nuevo_usuario_rol);
        nuevo_usuario_rol.setBounds(70, 270, 140, 30);
        jPanel2.add(nuevo_usuario_apellido);
        nuevo_usuario_apellido.setBounds(70, 210, 150, 30);
        jPanel2.add(nuevo_usuario_rut);
        nuevo_usuario_rut.setBounds(70, 90, 150, 30);
        jPanel2.add(nuevo_usuario_nombre);
        nuevo_usuario_nombre.setBounds(70, 150, 150, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 120, 300, 420);

        table_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDO", "ROL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_usuarios);
        if (table_usuarios.getColumnModel().getColumnCount() > 0) {
            table_usuarios.getColumnModel().getColumn(0).setResizable(false);
            table_usuarios.getColumnModel().getColumn(1).setResizable(false);
            table_usuarios.getColumnModel().getColumn(2).setResizable(false);
            table_usuarios.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(330, 120, 420, 420);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Bytes7575.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 30, 119, 48);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        agregar();
        LimpiarTabla();
        listar();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void table_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_usuariosMouseClicked
        int fila = table_usuarios.getSelectedRow();
        if (fila == -1) {
            Icon icono = new ImageIcon(getClass().getResource("/iconosjoption/seleccionar.png"));
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila",
                    "Alerta", JOptionPane.DEFAULT_OPTION, null);
        } else {
            String rut = table_usuarios.getValueAt(fila, 0).toString();
            String nombre = table_usuarios.getValueAt(fila, 1).toString();
            String apellido = table_usuarios.getValueAt(fila, 2).toString();
            nuevo_usuario_rut.setText(rut);
            nuevo_usuario_nombre.setText(nombre);
            nuevo_usuario_apellido.setText(apellido);
            nuevo_usuario_rut.setEditable(false);
            nuevo_usuario_rut.enable(false);

        }
    }//GEN-LAST:event_table_usuariosMouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

        Modificar();
        LimpiarTabla();
        listar();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        eliminar();
        LimpiarTabla();
        listar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    void Limpiar() {
        nuevo_usuario_rut.setText("");
        nuevo_usuario_nombre.setText("");
        nuevo_usuario_apellido.setText("");
        nuevo_usuario_rut.setEditable(true);
        nuevo_usuario_rut.enable(true);
    }

    void LimpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    void agregar() {
        int rol;
        if (nuevo_usuario_rut.getText().equals("") || nuevo_usuario_nombre.getText().equals("")
                || nuevo_usuario_apellido.getText().equals("")) {
            Icon icono = new ImageIcon(getClass().getResource("/iconosjoption/advertencia.png"));
            JOptionPane.showMessageDialog(null, "Hay campos vacios", "Alerta", JOptionPane.DEFAULT_OPTION, null);
        } else {
            String rut = nuevo_usuario_rut.getText();
            String nombre = nuevo_usuario_nombre.getText();
            String apellido = nuevo_usuario_apellido.getText();
            if (nuevo_usuario_rol.getSelectedItem() == "Administrador") {
                rol = 1;
            } else {
                rol = 2;
            }

            Object[] ob = new Object[4];
            ob[0] = rut;
            ob[1] = nombre;
            ob[2] = apellido;
            ob[3] = rol;
            usql.add(ob);
            Icon icono = new ImageIcon(getClass().getResource("/iconosjoption/agregar.png"));
            JOptionPane.showMessageDialog(null, "Usuario Agregado Exitosamente!!", "Confirmacion", JOptionPane.DEFAULT_OPTION, null);
            Limpiar();
            System.out.println("rut:" + rut + " nombre:" + nombre + " apellido:" + apellido + " rol:" + rol);
        }
    }

    void Modificar() {
        int rol;
        if (nuevo_usuario_rut.getText().equals("") || nuevo_usuario_nombre.getText().equals("")
                || nuevo_usuario_apellido.getText().equals("")) {
            Icon icono = new ImageIcon(getClass().getResource("/iconosjoption/advertencia.png"));
            JOptionPane.showMessageDialog(null, "Hay campos vacios", "Alerta", JOptionPane.DEFAULT_OPTION, null);
        } else {
            String rut = nuevo_usuario_rut.getText();
            String nombre = nuevo_usuario_nombre.getText();
            String apellido = nuevo_usuario_apellido.getText();
            if (nuevo_usuario_rol.getSelectedItem() == "Administrador") {
                rol = 1;
            } else {
                rol = 2;
            }

            Object[] ob = new Object[4];
            ob[0] = nombre;
            ob[1] = apellido;
            ob[2] = rol;
            ob[3] = rut;
            usql.actualizar(ob);
            Icon icono = new ImageIcon(getClass().getResource("/iconosjoption/modificar.png"));
            JOptionPane.showMessageDialog(null, "Datos actualizado", "Confirmacion", JOptionPane.DEFAULT_OPTION, null);
            Limpiar();
        }
    }
    
    void eliminar(){
         if (nuevo_usuario_rut.getText().equals("")) {
            Icon icono = new ImageIcon(getClass().getResource("/iconosjoption/advertencia.png"));
            JOptionPane.showMessageDialog(null, "Rut erroneo", "Alerta", JOptionPane.DEFAULT_OPTION, null);
        } else {
             String rut = nuevo_usuario_rut.getText();

            Object[] ob = new Object[1];
            ob[0] = rut;
            usql.eliminar(rut);
            
            usql.eliminar(rut);
            Icon icono = new ImageIcon(getClass().getResource("/iconosjoption/eliminar.png"));
            JOptionPane.showMessageDialog(null, "Usuario eliminado Exitosamente!!", "Confirmacion", JOptionPane.DEFAULT_OPTION, null);
            Limpiar();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nuevo_usuario_apellido;
    private javax.swing.JTextField nuevo_usuario_nombre;
    private javax.swing.JComboBox<String> nuevo_usuario_rol;
    private javax.swing.JTextField nuevo_usuario_rut;
    private javax.swing.JTable table_usuarios;
    // End of variables declaration//GEN-END:variables
}
