/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.ConexionBD;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.EntidadProducto;
import sql.EntidadVenta;
import sql.ProductoSQL;
import sql.VentaSQL;

/**
 *
 * @author basti
 */
public class Ventana_venta extends javax.swing.JInternalFrame {

    String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;
    ConexionBD conexion = new ConexionBD();
    ProductoSQL ps = new ProductoSQL();
    DefaultTableModel modelo = new DefaultTableModel();
    EntidadVenta ev = new EntidadVenta();
    VentaSQL ventasql = new VentaSQL();
    EntidadProducto ep = new EntidadProducto();
    String codigobarra;
    int can, precio;

    /**
     * Creates new form Ventana_venta
     */
    public Ventana_venta() {
        initComponents();
        fecha();
        campos();
    }

    //obtener fecha actual de la pc
    void fecha() {
        Calendar calendar = new GregorianCalendar();
        lblFecha.setText("" + calendar.get(calendar.YEAR) + "-" + (calendar.get(calendar.MONTH) + 1) + "-" + calendar.get(calendar.DAY_OF_MONTH));
    }

    void campos() {
        txtNombreProducto.setEnabled(false);
        txtCantidadProducto.setEnabled(false);
        btnAgregar.setEnabled(false);
    }

    /*
   void hora() {

        Timer timer = new Timer();
        
        Date HORA = new Date();
        String ampm="hh:mm:ss a";
        SimpleDateFormat format = new SimpleDateFormat(ampm);
        Calendar hoy= Calendar.getInstance();
        txtHora.setText(String.format(format.format(HORA),hoy));
        
        //LocalTime horactual = LocalTime.now();
        //txtHora.setText(""+horactual);
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescuentoVenta = new javax.swing.JTextField();
        txtTotalVenta = new javax.swing.JTextField();
        txtIvaVenta = new javax.swing.JTextField();
        btnGenerarVenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        RB_IngresoManual = new javax.swing.JRadioButton();
        txtCodigoProducto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        btnCancelarVenta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new org.edisoncor.gui.varios.ClockDigital();
        lblVentaDescuento = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 249, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Hora");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 50, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Bytes50.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 260, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1360, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 630, 50, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Iva:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Descuento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 90, 30));

        txtDescuentoVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtDescuentoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, 80, 30));

        txtTotalVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalVenta.setEnabled(false);
        jPanel1.add(txtTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 630, 80, 30));

        txtIvaVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtIvaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 630, 80, 30));

        btnGenerarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/caja.png"))); // NOI18N
        btnGenerarVenta.setText("Generar Venta");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 160, 40));

        jPanel2.setLayout(null);

        txtCantidadProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtCantidadProducto);
        txtCantidadProducto.setBounds(20, 270, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Codigo");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 100, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 170, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 240, 70, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/carrito-de-compras.png"))); // NOI18N
        jLabel10.setText("Ingreso Productos");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 30, 160, 30);

        txtNombreProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtNombreProducto);
        txtNombreProducto.setBounds(20, 200, 140, 30);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/flecha-derecha.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        jPanel2.add(btnAgregar);
        btnAgregar.setBounds(40, 370, 120, 40);

        RB_IngresoManual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RB_IngresoManual.setText("Ingreso Manual");
        RB_IngresoManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB_IngresoManualMouseClicked(evt);
            }
        });
        jPanel2.add(RB_IngresoManual);
        RB_IngresoManual.setBounds(40, 320, 120, 25);

        txtCodigoProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyPressed(evt);
            }
        });
        jPanel2.add(txtCodigoProducto);
        txtCodigoProducto.setBounds(20, 130, 140, 30);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(120, 90, 73, 23);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 220, 430));

        jPanel3.setLayout(null);

        TablaProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio Unitario", "Cantidad", "Descuento", "Total"
            }
        ));
        TablaProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TablaProductosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 1050, 350);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 1090, 430));

        btnCancelarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        btnCancelarVenta.setText("Cancelar Venta");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 160, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Bytes50.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 70));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Punto de Venta ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 210, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Fecha");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 50, 30));

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 90, 30));

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 100, 40));

        lblVentaDescuento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lblVentaDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 630, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB_IngresoManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB_IngresoManualMouseClicked
        if (RB_IngresoManual.isSelected()) {
            txtNombreProducto.setEnabled(true);
            txtCantidadProducto.setEnabled(true);
            btnAgregar.setEnabled(true);
        } else {
            txtNombreProducto.setEnabled(false);
            txtCantidadProducto.setEnabled(false);
            btnAgregar.setEnabled(false);
        }
    }//GEN-LAST:event_RB_IngresoManualMouseClicked

    private void TablaProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaProductosKeyPressed

    }//GEN-LAST:event_TablaProductosKeyPressed

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        guardarventa();
        JOptionPane.showMessageDialog(null, "Ventana Realizada con exito", "Confirmacion",
                JOptionPane.DEFAULT_OPTION, null);
    }//GEN-LAST:event_btnGenerarVentaActionPerformed

    private void txtCodigoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyPressed

     
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                agregarproducto(); //Método que tienes que crearte
            }
        
    }//GEN-LAST:event_txtCodigoProductoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregarproducto();
        limpiarcampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        limpiarcampos();
        limpiartabla();
        JOptionPane.showMessageDialog(null, "Venta cancelada", "Alerta", JOptionPane.CANCEL_OPTION, null);
        System.out.println("" + codigobarra);
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    void limpiarcampos() {
        txtCodigoProducto.setText("");
        txtNombreProducto.setText("");
        txtCantidadProducto.setText("");
        lblVentaDescuento.setText("");
    }

    void limpiartabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    void guardarventa() {
        int nu_venta_PK = 1;
        String fecha = lblFecha.getText();
        int total_monto = 2500;

        ev.setNum_venta_pk(nu_venta_PK);
        ev.setFecha_venta(fecha);
        ev.setMonto_venta(total_monto);

        ventasql.Guardar_Venta(ev);
    }

    void buscarproducto() {
        if (txtCodigoProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar codigo producto", "Alerta", JOptionPane.DEFAULT_OPTION, null);
        } else {
            String codigobarra = txtCodigoProducto.getText();
            ep = ps.listarID(codigobarra);
            if (ep.getCodigo() != " ") {
                ep = ps.listarID(codigobarra);
                txtNombreProducto.setText("" + ep.getNombre());
                System.out.println("" + ep.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "Producto inexistente", "Alerta", JOptionPane.DEFAULT_OPTION, null);
            }
        }
    }

    void agregarproducto() {

        if (txtCodigoProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese codigo de producto", "Alerta", JOptionPane.DEFAULT_OPTION, null);
        } else {
            int total, descuento, iva, cantidadproducto;
            modelo = (DefaultTableModel) TablaProductos.getModel();
            can = 1;
            //capturar nombre
            ep = ps.listarID(codigobarra);
            codigobarra = txtCodigoProducto.getText();
            String nombre = ep.getNombre();
            precio = ep.getPrecio();

            //fin
            total = can * ep.getPrecio();
            ArrayList lista = new ArrayList();
            lista.add(codigobarra);
            lista.add(nombre);
            lista.add(precio);
            lista.add(can);
            lista.add(0);
            lista.add(total);
            Object[] ob = new Object[6];
            ob[0] = lista.get(0);
            ob[1] = lista.get(1);
            ob[2] = lista.get(2);
            ob[3] = lista.get(3);
            ob[4] = lista.get(4);
            ob[5] = lista.get(5);
            modelo.addRow(ob);
            TablaProductos.setModel(modelo);
            calculartotal();
            lista.clear();
        }
    }

    void calculartotal() {
        int totalpago = 0;
        for (int i = 0; i < TablaProductos.getRowCount(); i++) {
            can = Integer.parseInt(TablaProductos.getValueAt(i, 3).toString());
            precio = Integer.parseInt(TablaProductos.getValueAt(i, 2).toString());
            totalpago = totalpago + (can * precio);
//            System.out.println("" + totalpago);

        }
        txtTotalVenta.setText("" + totalpago);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RB_IngresoManual;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnGenerarVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFecha;
    private org.edisoncor.gui.varios.ClockDigital lblHora;
    private javax.swing.JLabel lblVentaDescuento;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtDescuentoVenta;
    private javax.swing.JTextField txtIvaVenta;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
